#!/bin/bash
# Update htmx js library in the static/js catalog.

CMDS="wget"
URL="https://unpkg.com/htmx.org/dist/htmx.min.js"
TARGET_FILE="htmx.min.js"
STATIC_JS_DIR="./static/js"

for cmd in $CMDS; do
	command -v "$cmd" > /dev/null || { echo "command $cmd not found" && exit 1; }
done

wget "$URL" -O "$STATIC_JS_DIR/$TARGET_FILE"
